# Generated by Django 5.2.17 on 2026-09-22 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jugadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=60, unique=True)),
                ('nombre', models.CharField(max_length=120)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('pais', models.CharField(max_length=80)),
                ('nivel', models.PositiveIntegerField(default=1)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
