# Generated by Django 5.2.17 on 2026-09-22 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0001_initial'),
        ('torneos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jugadores',
            new_name='Jugador',
        ),
    ]
