# Generated by Django 5.2.17 on 2026-09-22 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Videojuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('genero', models.CharField(max_length=80)),
                ('plataforma', models.CharField(max_length=80)),
                ('clasificacion', models.CharField(blank=True, max_length=30)),
                ('fecha_lanzamiento', models.DateField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
    ]
